name: pyeas
channels:
  - defaults
  - conda-forge
dependencies:
  - click
  - fastparquet
  - graphviz
  - ipython
  - jupyter
  - matplotlib
  - numpy
  - openpyxl
  - pandas
  - pyarrow
  - python-dotenv
  - python-graphviz
  - python=3.11
  - pyyaml
  - s3fs
  - scikit-learn
  - seaborn
  - tabulate
  - pytest
  - nbstripout
